--회원 테이블 생성
DROP TABLE MEMBER;
CREATE TABLE MEMBER(
USERID VARCHAR2(20),
PW VARCHAR2 (20) NOT NULL,
BIRTH VARCHAR2(4),
REGDATE DATE DEFAULT SYSDATE,
CONSTRAINT PK_USERID PRIMARY KEY(USERID) --PK가 아이디 코드다.
);

SELECT *
FROM MEMBER;

--SELECTLIST
SELECT * FROM MEMBER;
--SELECTONE
SELECT * FROM MEMBER
WHERE USERID = 'java';


--insert
INSERT INTO MEMBER (USERID,PW,BIRTH)VALUES('SHIN', 'S11', 1106);
INSERT INTO MEMBER (USERID,PW,BIRTH)VALUES('PARK', 'P11', 0706);
INSERT INTO MEMBER (USERID,PW,BIRTH)VALUES('SONG', 'S21', 1025);


COMMIT;
ROLLBACK;


--update
UPDATE MEMBER 
SET PW = 1004, BIRTH = 0503
WHERE USERID = 'java'; --PK는 변경이 어렵다.


--delete
DELETE FROM MEMBER
WHERE BIRTH=0527;

DELETE FROM MEMBER
WHERE USERID = 'SHIN';

