DROP VIEW DAYITEM_SALES_VIEW;

CREATE VIEW DAYITEM_SALES_VIEW --'DAYITEM_SALES_VIEW'라는 이름으로 뷰를 만들겠다.
AS
SELECT I.ITEMCODE, I.ITEMNAME, I.PRICE,  NVL(S.AMOUNT, 0) AMOUNT, I.REGDATE, NVL(I.NOTE, ' ') NOTE
      FROM ITEM I LEFT JOIN
                           (SELECT SALESDATE, ITEMCODE, SUM(AMOUNT)AMOUNT
                             FROM SALES
                            WHERE SALESDATE = '2021-04-29'
                       GROUP BY SALESDATE, ITEMCODE) S
          ON I.ITEMCODE = S.ITEMCODE
ORDER BY I.ITEMCODE;

--뷰를 조회하는 방법
--뷰를 만들어놓으면 자바에서 이 명령문만 실행해도 됨.
--장점 : 코드가 간결해짐.

SELECT * FROM DAYITEM_SALES_VIEW;


--CREATE VIEW MEMBER_VIEW
--AS
--SELECT * FROM MEMBER;
--이렇게 만들면 누구나 볼 수 있는 정보가 된다
--프라이버시 보장해주세요 !!
--비밀번호를 안 보이게 하려면 ?

DROP VIEW MEMBER_VIEW;
CREATE VIEW MEMBER_VIEW
AS
SELECT USERID, BIRTH, REGDATE FROM MEMBER;

SELECT * FROM MEMBER_VIEW;

--비밀번호 2자리만 보여주고 싶다면 ?
SELECT SUBSTR('1234', 2) FROM DUAL; --임시테이블 DUAL에서 샘플로 테스트해보겠다.
SELECT SUBSTR('01234567', 3,3) FROM DUAL;
SELECT SUBSTR('012457',1,2) ||'***' FROM DUAL;
SELECT SUBSTR('0157',1,2) ||'******' PW_TEST FROM DUAL;

CREATE VIEW MEMBER_VIEW
AS
SELECT USERID, SUBSTR(PW, 1,2) ||'**' PW, BIRTH, REGDATE FROM MEMBER;

--권한을 뺏을 때는
--REVOKE SELECT ON MEMBER FROM HR;

DROP VIEW SAMPLE_VIEW;
CREATE VIEW SAMPLE_VIEW
AS
SELECT S.*, I.ITEMNAME, IA.QTY QTY_AVG
FROM SALES S INNER JOIN ITEM I ON (I.ITEMCODE = S.ITEMCODE)
INNER JOIN (SELECT ITEMCODE, AVG(QTY) QTY FROM SALES GROUP BY ITEMCODE) IA ON (S.ITEMCODE = IA.ITEMCODE);

SELECT * FROM SAMPLE_VIEW;
--29일에 판매된 리스트만 보고 싶다면 ?

SELECT * FROM SAMPLE_VIEW
WHERE SALESDATE = '2021-04-29';

COMMIT;








