--GUEST BOOK
--이름, 메일 주소, 비밀번호(수정 시 사용할), 인사말, 등록 일자
--PK로 잡을만한 게 없으니까 순번 추가.

DROP TABLE GUEST_BOOK;

CREATE TABLE GUEST_BOOK(
SEQ NUMBER(3),
NAME VARCHAR2(20),
MAIL VARCHAR2(30),
PW VARCHAR2(20),
CONTENT VARCHAR2(200),
REGDATE DATE DEFAULT SYSDATE,
PRIMARY KEY (SEQ)
);

SELECT * FROM GUEST_BOOK;